# Generated by Django 5.2.17 on 2026-09-14 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, default='')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
